package com.wdf.location.response;

public enum ResponseCodes {

	OK, INTERNAL_SERVER_ERROR, INVALID_LEVEL_FOR_A_CHILD, BLANK_NAME, BLANK_TYPE, EMPTY_TAG_LIST, BLANK_STATUS, ILLEGAL_STATUS_VALUE, NO_CHILD_LOCATION_IN_DB, NO_PARENT_LOCATION_IN_DB

}
